name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Django settings
      run: |
        echo "from .base import *" > config/settings/test.py
        echo "DEBUG = True" >> config/settings/test.py
        echo "DATABASES = {" >> config/settings/test.py
        echo "    'default': {" >> config/settings/test.py
        echo "        'ENGINE': 'django.db.backends.sqlite3'," >> config/settings/test.py
        echo "        'NAME': BASE_DIR / 'test_db.sqlite3'," >> config/settings/test.py
        echo "    }" >> config/settings/test.py
        echo "}" >> config/settings/test.py

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

    - name: Coverage report
      run: coverage run --source='.' manage.py test && coverage report
