name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Django test settings
      run: |
        mkdir -p config/settings
        echo "from .base import *" > config/settings/test.py
        echo "DEBUG = True" >> config/settings/test.py
        echo "DATABASES = {" >> config/settings/test.py
        echo "    'default': {" >> config/settings/test.py
        echo "        'ENGINE': 'django.db.backends.sqlite3'," >> config/settings/test.py
        echo "        'NAME': BASE_DIR / 'test_db.sqlite3'," >> config/settings/test.py
        echo "    }" >> config/settings/test.py
        echo "}" >> config/settings/test.py

    - name: Run migrations
      run: python manage.py migrate --settings=config.settings.test

    - name: Run tests
      run: python manage.py test --settings=config.settings.test

    - name: Coverage report
      run: |
        pip install coverage
        coverage run --source='.' manage.py test --settings=config.settings.test
        coverage report

