name: Django API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage

    - name: Create test settings for API
      run: |
        mkdir -p config/settings
        echo "" > config/__init__.py
        echo "" > config/settings/__init__.py

        echo "from pathlib import Path" > config/settings/test.py
        echo "BASE_DIR = Path(__file__).resolve().parent.parent.parent" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "SECRET_KEY = 'test-secret-key'" >> config/settings/test.py
        echo "DEBUG = True" >> config/settings/test.py
        echo "ALLOWED_HOSTS = []" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "INSTALLED_APPS = [" >> config/settings/test.py
        echo "    'django.contrib.admin'," >> config/settings/test.py
        echo "    'django.contrib.auth'," >> config/settings/test.py
        echo "    'django.contrib.contenttypes'," >> config/settings/test.py
        echo "    'django.contrib.sessions'," >> config/settings/test.py
        echo "    'django.contrib.messages'," >> config/settings/test.py
        echo "    'django.contrib.staticfiles'," >> config/settings/test.py
        echo "    'rest_framework'," >> config/settings/test.py
        echo "    'rest_framework_simplejwt'," >> config/settings/test.py
        echo "    'guardian'," >> config/settings/test.py
        echo "    'authentication'," >> config/settings/test.py
        echo "    'roles'," >> config/settings/test.py
        echo "    'permissions'," >> config/settings/test.py
        echo "]" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "MIDDLEWARE = [" >> config/settings/test.py
        echo "    'django.middleware.security.SecurityMiddleware'," >> config/settings/test.py
        echo "    'django.contrib.sessions.middleware.SessionMiddleware'," >> config/settings/test.py
        echo "    'django.middleware.common.CommonMiddleware'," >> config/settings/test.py
        echo "    'django.middleware.csrf.CsrfViewMiddleware'," >> config/settings/test.py
        echo "    'django.contrib.auth.middleware.AuthenticationMiddleware'," >> config/settings/test.py
        echo "    'django.contrib.messages.middleware.MessageMiddleware'," >> config/settings/test.py
        echo "    'django.middleware.clickjacking.XFrameOptionsMiddleware'," >> config/settings/test.py
        echo "]" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "ROOT_URLCONF = 'config.urls'" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "DATABASES = {" >> config/settings/test.py
        echo "    'default': {" >> config/settings/test.py
        echo "        'ENGINE': 'django.db.backends.sqlite3'," >> config/settings/test.py
        echo "        'NAME': BASE_DIR / 'test_db.sqlite3'," >> config/settings/test.py
        echo "    }" >> config/settings/test.py
        echo "}" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "REST_FRAMEWORK = {" >> config/settings/test.py
        echo "    'DEFAULT_PERMISSION_CLASSES': [" >> config/settings/test.py
        echo "        'rest_framework.permissions.IsAuthenticated'," >> config/settings/test.py
        echo "    ]," >> config/settings/test.py
        echo "    'DEFAULT_AUTHENTICATION_CLASSES': [" >> config/settings/test.py
        echo "        'rest_framework_simplejwt.authentication.JWTAuthentication'," >> config/settings/test.py
        echo "    ]" >> config/settings/test.py
        echo "}" >> config/settings/test.py
        echo "" >> config/settings/test.py
        echo "AUTHENTICATION_BACKENDS = [" >> config/settings/test.py
        echo "    'django.contrib.auth.backends.ModelBackend'," >> config/settings/test.py
        echo "    'guardian.backends.ObjectPermissionBackend'," >> config/settings/test.py
        echo "]" >> config/settings/test.py


    - name: Run migrations
      run: python manage.py migrate --settings=config.settings.test

    - name: Run API tests with coverage
      run: |
        coverage run manage.py test --settings=config.settings.test
        coverage report

